apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: web
  name: web
spec:
  selector:
    matchLabels:
      name: web
  replicas: 1
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: gcr.io/dokusho-199010/dokusho-web:latest
        name: web
        resources:
          requests:
            cpu: "50m"
        ports:
        - containerPort: 3000
          name: web-port