matrix:
  include:
    - language: node_js
      node_js:
        - "8"
      cache: yarn
      before_script:
        - cd dokusho
      script: ["yarn add coveralls", "yarn bsb -clean-world -make-world", "yarn ci"]

    - language: scala
      jdk: oraclejdk9
      scala: 
        - 2.12.9
      before_script:
        - cd dokusho-server
      script: 
        - sbt test