apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: backend
  name: backend
spec:
  replicas: 2
  selector:
    name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
      - image: gcr.io/dokusho-199010/dokusho-server
        name: backend
        ports:
        - containerPort: 8080
          name: backend-server
