apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: gcr.io/dokusho-199010/dokusho-frontend:latest
        imagePullPolicy: Never
        name: web
        ports:
        - containerPort: 3000
          name: http-server